// FLIGHT LAB — curriculum.js
// The textbook: 16 chapters in the order of the publicly described ANA cadet basic training (London ground school
// in English → Piper Archer at Sanford → visual navigation, crosswinds, diversions → instrument flying → Piper
// Seminole → CRM / TEM / jets / automation). Each chapter: Japanese explanation, English terms, examples, cautions,
// two check questions with the reasons, references. This is an UNOFFICIAL self-study text based on public
// information; it is not ANA's material and does not reproduce any SOP.
(function (FL) {
  'use strict';
  const R = {
    ana1: { label: 'ANA「ボーイング777 パイロットになるまで Phase2〜基礎訓練編〜」', url: 'https://www.ana.co.jp/group/777_30th/20251022_2.html' },
    ana2: { label: 'ANA「未来の翼が生まれる場所へ〜フロリダの空で見た、ANAのDNA〜」', url: 'https://www.anahd.co.jp/ana_news/2025/10/28/20251028.html' },
    acron: { label: 'Acron Aviation USA — Aircraft fleet', url: 'https://acronaviationacademy.com/usa/about-us/aircraft-fleet/' },
    archer: { label: 'Piper Archer TX（Piper 公式）', url: 'https://www.piper.com/model/archer-tx/' },
    seminole: { label: 'Piper Seminole（Piper 公式）', url: 'https://www.piper.com/model/seminole/' },
    g1000: { label: 'Garmin G1000 Cockpit Reference Guide — Piper PA-28-181 Archer', url: 'https://static.garmin.com/pumac/190-01460-00_0A_Web.pdf' },
    sfb: { label: 'FAA From the Flight Deck: Orlando Sanford (SFB)', url: 'https://www.faa.gov/flight_deck/sfb' },
    afh: { label: 'FAA Airplane Flying Handbook（FAA-H-8083-3）', url: 'https://www.faa.gov/regulations_policies/handbooks_manuals/aviation/airplane_handbook' },
    phak: { label: "FAA Pilot's Handbook of Aeronautical Knowledge（FAA-H-8083-25）", url: 'https://www.faa.gov/regulations_policies/handbooks_manuals/aviation/phak' },
    ifh: { label: 'FAA Instrument Flying Handbook（FAA-H-8083-15B, PDF）', url: 'https://www.faa.gov/sites/faa.gov/files/regulations_policies/handbooks_manuals/aviation/FAA-H-8083-15B.pdf' },
    aim: { label: 'FAA Aeronautical Information Manual（AIM）', url: 'https://www.faa.gov/air_traffic/publications/atpubs/aim_html/' },
    pcg: { label: 'FAA Pilot/Controller Glossary', url: 'https://www.faa.gov/air_traffic/publications/atpubs/pcg_html/' },
    wx: { label: 'FAA Aviation Weather Handbook（FAA-H-8083-28）', url: 'https://www.faa.gov/regulationspolicies/handbooksmanuals/aviation/faa-h-8083-28-aviation-weather-handbook' },
    rmh: { label: 'FAA Risk Management Handbook（FAA-H-8083-2A）', url: 'https://www.faa.gov/regulationspolicies/handbooksmanuals/risk-management-handbook-faa-h-8083-2a' },
    wb: { label: 'FAA Aircraft Weight and Balance Handbook（FAA-H-8083-1, PDF）', url: 'https://www.faa.gov/sites/faa.gov/files/regulations_policies/handbooks_manuals/aviation/FAA-H-8083-1.pdf' },
    tem: { label: 'SKYbrary: Threat and Error Management (TEM)', url: 'https://skybrary.aero/articles/threat-and-error-management-tem' },
    crm: { label: 'SKYbrary: Crew Resource Management (CRM)', url: 'https://skybrary.aero/articles/crew-resource-management-crm' },
    mag: { label: 'NOAA 磁気偏差計算（Magnetic Field Calculators）', url: 'https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml' },
    vfr: { label: 'FAA VFR Charts', url: 'https://www.faa.gov/air_traffic/flight_info/aeronav/digital_products/vfr/' },
  };
  // the six steps of the publicly described course (facts from ANA's pages; the per-step content here is a study plan)
  const PHASES = [
    { id: 'p1', no: 1, title: 'London：英語によるグラウンドスクール', en: 'Ground school in English (London)', fact: 'ANA の公開情報：座学は現在ロンドンで行い、授業はすべて英語。航空管制通信のシミュレーションも行う。', chapters: [1, 4, 5, 6, 7] },
    { id: 'p2', no: 2, title: 'Sanford：Piper Archer による基礎操縦', en: 'Basic flying on the Piper Archer (Sanford)', fact: 'ANA の公開情報：フライトはフロリダ州 Sanford 空港に隣接する訓練所で、単発機 Piper Archer を使用。90〜120 分のレッスン 12 回と審査（Check Flight）を経てソロへ。現地取材では平均 11 回目でファーストソロ。', chapters: [2, 3, 8, 9, 10, 11] },
    { id: 'p3', no: 3, title: '目視航法・横風・目的地変更', en: 'Visual navigation, crosswinds, diversions', fact: 'ANA の公開情報：地図に線を引き上空の風から針路を計算して目的地へ飛ぶ Navigation 訓練。目的地変更に伴う再計算、エンジン停止の想定、現在地を見失った場合の対処も並行して訓練。', chapters: [12, 14] },
    { id: 'p4', no: 4, title: '計器飛行の導入', en: 'Introduction to instrument flying', fact: 'ANA の公開情報：計器のみを頼りに飛ぶ計器飛行の訓練を行う。', chapters: [13] },
    { id: 'p5', no: 5, title: 'Piper Seminole への移行', en: 'Transition to the Piper Seminole', fact: 'ANA の公開情報：双発機 Piper Seminole で片発停止や機材故障の対応を訓練し、最後の Check Flight を経てライセンスを取得。', chapters: [15] },
    { id: 'p6', no: 6, title: 'CRM・TEM・ジェット機・自動化への準備', en: 'Preparing for CRM, TEM, jets and automation', fact: '公開情報：基礎訓練の後は副操縦士任用訓練でエアラインの大型機の免許を目指す（ANA の現地取材記事）。この段階の内容は本教材の一般的な準備学習で、ANA の訓練内容の再現ではない。', chapters: [16] },
  ];
  const ch = (o) => o;
  const CHAPTERS = [
    ch({
      no: 1, phase: 'p1', title: 'ANA 公開課程と学習計画', en: 'The published course and a study plan',
      summary: 'ANA が公開している基礎訓練の流れを、事実と推測に分けて確認し、本アプリでの学び方を決める。',
      body: [
        '<b>事実（ANA の公開情報）：</b>自社養成パイロット訓練生の基礎訓練は約 1 年半〜2 年。現在は Acron Aviation 社に一部を委託し、イギリス・ロンドンで座学（授業はすべて英語）、アメリカ・フロリダ州 Sanford 空港に隣接する訓練所でフライトを行う。',
        'フライトは単発機 Piper Archer から始まり、1 回 90〜120 分のレッスン 12 回と審査（Check Flight）に合格するとソロ（単独飛行）ができるようになる。その後、地図と上空の風から針路を計算して目的地へ飛ぶ Navigation 訓練（目的地変更・エンジン停止の想定・現在地を見失った場合の対処を含む）、計器飛行、双発機 Piper Seminole での片発停止・故障対応へと進む。',
        '現地取材の記事では、訓練所に 4 本の滑走路を持つ Sanford 国際空港で旅客機と訓練機が混在すること、平均 11 回目のフライトでファーストソロに出ること、「準備に始まり、準備に終わる」という考え方が紹介されている。',
        '<b>推測・未確認：</b>ANA の社内 SOP、正式な審査基準、各機体の個別の仕様は公開情報からは確定できない。本アプリの速度・高度・許容差はすべて「仮想教材値」で、実機訓練の基準ではない。',
        '<b>学び方：</b>各章を読み、確認問題に答え、対応する飛行課題を「導入→基礎→精度」の順に試す。振り返りメモを書き、学習記録に残す（正式な飛行日誌ではない）。',
      ],
      terms: [['Cadet pilot', '自社養成パイロット訓練生', ''], ['Ground school', '座学', 'ロンドンで英語'], ['Lesson / Sortie', 'レッスン・1 回の飛行', ''], ['Check flight', '審査飛行', ''], ['First solo', '初単独飛行', ''], ['Navigation (cross-country)', '航法訓練', '目的地へ飛ぶ'], ['Multi-engine', '双発', 'Piper Seminole']],
      examples: ['今週の計画：第 6 章を読む → 課題 1「直線水平飛行」を導入で 3 回 → 振り返りに「高度が下がりがちだったのはトリム不足」と書く。', '公開情報の「12 回のレッスン」は事実、「各レッスンの細かい内容」は公開されていないので推測しない。'],
      cautions: ['本アプリは ANA の公式教材ではない。実機訓練・教官の指示・POH/AFM・SOP・航空法規を優先する。', 'アプリの課題を達成しても、ソロや資格の可否とは関係しない。'],
      quiz: [
        { q: 'ANA の公開情報で、フライト訓練の最初に使うと書かれている機体は？', choices: ['Piper Archer', 'Piper Seminole', 'Boeing 777', 'Cirrus SR20'], answer: 0, why: '公開情報では単発機 Piper Archer で始め、その後双発機 Piper Seminole に進む。' },
        { q: '本アプリの速度・高度・許容差の扱いとして正しいものは？', choices: ['ANA の審査基準そのもの', '実機の POH の値', '仮想教材値（実機・審査基準ではない）', 'FAA の実技試験基準'], answer: 2, why: '公開情報では審査基準や社内 SOP は確定できないため、本アプリの数値は仮想教材値として扱う。' },
      ],
      refs: [R.ana1, R.ana2, R.acron], tasks: ['t1'],
    }),
    ch({
      no: 2, phase: 'p2', title: 'G1000 型計器の配置', en: 'The G1000-type cockpit layout',
      summary: 'PFD（左）・MFD（右）・オーディオパネル（中央）の役割と、どこに何が出るかを覚える。',
      body: [
        '<b>事実（Piper の公開情報）：</b>現行の Piper Archer TX は Garmin G1000 NXi を標準装備し、10.4 インチの PFD と MFD、GMA 1360 デジタル・オーディオパネル、Garmin G5 スタンバイを備える（オプションに GFC 700 オートパイロットなど）。Acron Aviation の公開ページも、Archer と Seminole の G1000 搭載を挙げている。',
        '<b>PFD（Primary Flight Display）：</b>中央に姿勢、左に速度テープ、右に高度テープと昇降計、下に HSI（方位とコース）。上部に NAV・COM の周波数、選択高度（ALT SEL）と気圧設定（BARO）は高度テープの上下に出る。Garmin の Archer 用リファレンスガイドでは、BARO ノブで気圧設定、PFD ソフトキー → STD BARO で 29.92、ALT UNIT で inHg / hPa の切替、CDI ソフトキーで GPS → VOR1(LOC1) → VOR2(LOC2) → GPS の順に航法ソースを切り替える。',
        '<b>MFD（Multi-Function Display）：</b>左にエンジン表示（Archer のガイドでは RPM、EGT、燃料流量、油圧、油温、電流・電圧、燃料量）、右に地図（MAP）や飛行計画（FPL）。',
        '<b>本アプリの表示：</b>G1000 の完全な再現ではなく「G1000 型の配置と基本概念を学ぶ教材」。エンジン表示は、このアプリのモデルが計算している値（RPM、出力、燃料流量、燃料量）だけを出し、計算していない値（油圧・油温・EGT・電流など）は架空の正常値を出さず「—」と表示する。オートパイロットは実装していない（HDG や ALT を変えても機体は自動で追従しない）。',
      ],
      terms: [['PFD', '主飛行表示', '姿勢・速度・高度・方位'], ['MFD', '多機能表示', '地図・エンジン'], ['HSI', '水平状況指示器', '方位とコース'], ['Heading bug', '方位バグ', '目標方位の目印'], ['Selected altitude', '選択高度', ''], ['Altimeter setting (BARO)', '高度計規正値', 'inHg / hPa'], ['CDI', 'コース偏位指示', 'GPS / VOR / LOC'], ['Softkey', 'ソフトキー', '画面下のボタン']],
      examples: ['離陸前に BARO を管制の QNH（例 29.98）に合わせ、ALT SEL を最初の指定高度に、HDG バグを滑走路方位に合わせる。', 'CDI ソフトキーを押して GPS（マゼンタ）から VOR1（緑）に切り替え、HSI の針の色が変わるのを確認する。'],
      cautions: ['機体ごとにソフトウェアの版やオプションが違い、表示や操作が異なる。実機の操作は機体のガイドと教官の指示で確認する（機体ごとに要確認）。', '本アプリの PFD・MFD は航法に使えない（NOT FOR NAVIGATION）。'],
      quiz: [
        { q: 'G1000 型の配置で、速度テープがあるのはどこ？', choices: ['PFD の左側', 'PFD の右側', 'MFD の左側', 'オーディオパネル'], answer: 0, why: 'PFD の左に速度（Airspeed）、右に高度（Altitude）と昇降計（VSI）が並ぶ。' },
        { q: '本アプリで油圧（OIL PSI）が「—」と表示される理由は？', choices: ['エンジンが故障している', 'このアプリのモデルが油圧を計算していないため、架空の正常値を出さない', '計器の電源が切れている', 'ソフトキーで非表示にしている'], answer: 1, why: '実装していない値に「それらしい正常値」を出すと誤学習につながるため、「—」と表示する。' },
      ],
      refs: [R.archer, R.acron, R.g1000], tasks: ['t1', 't11'],
    }),
    ch({
      no: 3, phase: 'p2', title: 'Sanford 空港の地上・空域', en: 'Sanford: the ground and the airspace',
      summary: '平行 3 本＋交差 1 本の滑走路、Hot Spot、Class C と Orlando Class B を、公開情報から整理する。',
      body: [
        '<b>事実（FAA「From the Flight Deck: SFB」）：</b>Orlando Sanford（SFB）は Orlando International の北約 20 マイル。滑走路は 9/27 の L・C・R（進入端の位置がずれた平行 3 本）と、交差する 18/36。滑走路の取り違えが起きやすい空港とされる。空域は Class C で、その上に Orlando の Class B がかぶっている。',
        'SFB 管制塔の情報として、9L/27R が主要運用滑走路、9R/27L が主要な飛行訓練用滑走路。Line Up and Wait（LUAW）を使う。場周では upwind・crosswind・base をそれぞれ約 1 マイルで飛ぶことを求めている。',
        '<b>Hot Spot HS1：</b>誘導路 C と滑走路 27C の標示が取り違えられやすい。滑走路 18 などに着陸して 18 から誘導路 C へ右折するはずが、滑走路 27C へ右折してしまった誤進入の例がある。滑走路の標示は白、誘導路などの標示は黄色。迷ったら管制に確認する。',
        '<b>L / C / R の識別：</b>同じ向きの平行滑走路は、その向きに進入するときの左から L・C・R。9 方向（東向き）なら北側が 9L、南側が 9R。反対向き（27）では左右が入れ替わり、9L の反対端は 27R になる。',
        '<b>旅客機と訓練機の混在：</b>現地取材の記事は、訓練生の小型機と多くの旅客機が行き交う中で、英語の交信を聞きながら高い状況認識が求められると紹介している。',
      ],
      terms: [['Class C airspace', 'Class C 空域', '入域前に双方向交信'], ['Class B airspace', 'Class B 空域', '入域に許可が必要'], ['Hot spot', 'ホットスポット', '誤進入が起きやすい場所'], ['Hold short', '手前で停止', ''], ['Runway incursion', '滑走路誤進入', ''], ['Wrong surface landing', '誤った面への着陸', ''], ['Parallel runways L/C/R', '平行滑走路の左・中央・右', '']],
      examples: ['「Runway 27 Center」の指示を受けたら、27 方向（西向き）で真ん中の滑走路。9C の反対端。', '滑走路 18 に着陸後「exit right on Charlie」と言われたら、白い標示（滑走路）ではなく黄色い標示（誘導路 C）へ入ることを確認する。'],
      cautions: ['本アプリの空港図は模式図（NOT FOR NAVIGATION）。位置・角度は概略で、実際の運航には FAA の最新空港図・Chart Supplement・NOTAM を使う。', '空域の範囲・高度は本アプリでは判定しない。'],
      quiz: [
        { q: '東向き（9 方向）に進入するとき、3 本の平行滑走路の南側の滑走路は？', choices: ['9L', '9C', '9R', '27R'], answer: 2, why: '進入する向きから見て右が R。東向きでは右手＝南側なので 9R。' },
        { q: 'FAA が SFB の Hot Spot HS1 として注意しているのは？', choices: ['誘導路 C と滑走路 27C の取り違え', '滑走路 18 の長さ不足', '鳥の多さだけ', '管制塔の運用時間'], answer: 0, why: '誘導路 C と滑走路 27C の標示が取り違えられ、滑走路誤進入につながった例がある。' },
      ],
      refs: [R.sfb, R.ana2, R.vfr, R.aim], tasks: ['t5', 't6'],
    }),
    ch({
      no: 4, phase: 'p1', title: '英語 ATC 復唱', en: 'Reading back ATC instructions in English',
      summary: '何を復唱するか、何をしてはいけないか（推測・他機の指示）を身につける。',
      body: [
        '<b>復唱（readback）の基本：</b>滑走路の指定、hold short の指示、高度・方位・周波数などの指示は、コールサインを付けて復唱する。FAA の SFB 情報は、滑走路指定・誘導路・hold short をコールサイン付きで同じ送信内に復唱することを求め、欠けた復唱は言い直しになると書いている。',
        '<b>Line up and wait：</b>滑走路に入って待つ指示で、離陸許可ではない。<b>Cleared for takeoff</b> を聞くまで離陸しない。',
        '<b>自分宛てか：</b>交信の最初のコールサインを必ず聞く。他機への指示に応答・行動しない。分からなければ確認する。',
        '<b>分からないとき：</b>「Say again」（もう一度）、「Verify …」（確認）、「Unable」（できない）。「Roger」は「受信した」、「Wilco」は「了解し従う」で、指示の復唱の代わりにはならない。',
        '本アプリの英語交信は、架空のコールサインと教材用の文例。ライブ ATC、音声認識、録音、送信は行わない。',
      ],
      terms: [['Readback', '復唱', ''], ['Call sign', 'コールサイン', ''], ['Line up and wait (LUAW)', '滑走路に入って待機', '離陸許可ではない'], ['Cleared for takeoff', '離陸許可', ''], ['Say again', 'もう一度言ってください', ''], ['Verify', '確認してください', ''], ['Unable', 'できません', ''], ['Wilco', '了解し従います', '']],
      examples: ['ATC：「Archer 7LA, hold short of Runway 27 Center at Charlie.」→「Hold short Runway 27 Center at Charlie, Archer 7LA.」', '他機宛て：「Cessna 4KP, cleared for takeoff.」→ 応答しない。待機を続ける。'],
      cautions: ['聞き取れなかった部分を推測で補って行動しない。', '本アプリの文例は実際の ATC 指示として使えない。'],
      quiz: [
        { q: '「Runway 9 Right, line up and wait.」を受けた後にしてよいことは？', choices: ['すぐ離陸する', '滑走路に入って停止し、離陸許可を待つ', '滑走路手前で停止したまま', '「Roger」とだけ言って離陸する'], answer: 1, why: 'LUAW は滑走路に入って待機する指示。離陸は cleared for takeoff を受けてから。' },
        { q: 'hold short の指示に対する正しい応答は？', choices: ['Roger', 'Wilco', '滑走路・hold short の内容・コールサインを復唱', '応答しない'], answer: 2, why: 'hold short はコールサイン付きで内容を復唱する必要がある。Roger / Wilco だけでは不十分。' },
      ],
      refs: [R.sfb, R.aim, R.pcg], tasks: [],
    }),
    ch({
      no: 5, phase: 'p1', title: '英語で基礎概念を説明する', en: 'Explaining the basics in English',
      summary: '座学が英語で行われる前提で、四つの力・迎角・失速などを英語で短く説明できるようにする。',
      body: [
        '公開情報では、ロンドンでの座学は「授業も全て英語」。用語を日本語で知っているだけでなく、英語で短く説明できることが大切になる。',
        '<b>型：</b>「定義 → 何が変えるか → 操縦でどう使うか」の 3 文で言う。例：「Angle of attack is the angle between the wing\'s chord line and the relative wind. It changes with pitch and airspeed. The wing stalls when it exceeds the critical angle of attack.」',
        '<b>よく使う表現：</b>increase / decrease、maintain、in order to、as a result、which means、in other words。',
        '<b>練習：</b>各章の英語用語表を見て、1 語ずつ英語で定義を言ってみる。本アプリの英語交信ページでは英文の読み上げ（音声合成）を聞ける。',
      ],
      terms: [['Lift', '揚力', ''], ['Weight', '重力（重量）', ''], ['Thrust', '推力', ''], ['Drag', '抗力', ''], ['Angle of attack', '迎角', ''], ['Critical angle of attack', '臨界迎角', ''], ['Relative wind', '相対風', ''], ['Trim', 'トリム', '']],
      examples: ['Q: Why does the airplane need more angle of attack at low speed? — A: Because lift depends on airspeed. At a lower speed, the wing needs a higher angle of attack to produce the same lift.', 'Q: What is a stall? — A: A stall happens when the angle of attack exceeds the critical angle. It can happen at any airspeed and any attitude.'],
      cautions: ['「失速＝速度が遅いこと」と覚えない。失速は迎角の問題（どんな速度・姿勢でも起こり得る）。', '英語の暗記ではなく、意味を自分の言葉で説明できるかを確かめる。'],
      quiz: [
        { q: '「A stall can occur at any airspeed」の意味として正しいのは？', choices: ['速度が十分なら絶対に失速しない', '迎角が臨界迎角を超えれば、どの速度でも失速し得る', '失速は低速でだけ起こる', '失速は高度の問題'], answer: 1, why: '失速は臨界迎角を超えることで起きる。急な引き起こしや大きなバンクでは高速でも起こる。' },
        { q: '「Relative wind」に最も近い日本語は？', choices: ['地上の風', '機体の運動と反対向きに当たる気流', '向かい風', '上昇気流'], answer: 1, why: '相対風は機体の飛行経路と平行・反対向きの気流。迎角はこれと翼弦線の角度。' },
      ],
      refs: [R.ana1, R.phak], tasks: [],
    }),
    ch({
      no: 6, phase: 'p1', title: '姿勢・四つの力・トリム', en: 'Attitude, the four forces and trim',
      summary: '姿勢と出力で飛行状態が決まること、トリムで操縦の力を抜くことを理解する。',
      body: [
        '<b>四つの力：</b>揚力（Lift）・重力（Weight）・推力（Thrust）・抗力（Drag）。安定した直線水平飛行では、おおむね揚力＝重力、推力＝抗力（つり合い）。',
        '<b>姿勢＋出力＝性能：</b>機首の姿勢（ピッチ）と出力の組み合わせで、速度と上昇・降下率がほぼ決まる。目標の姿勢を外の景色（または姿勢指示器）で作り、出力を合わせ、計器で結果を確かめる。',
        '<b>トリム：</b>操縦桿にかけ続けている力を打ち消す。手順は「姿勢を作る → 出力を合わせる → 安定を待つ → トリムで力を抜く」。トリムで機首を動かすのではなく、力を抜く道具として使う。',
        '<b>本アプリ：</b>[ / ] キーでトリム（教材モデル）。キー操作は既定で「離すとその機首角を保つ」補助が働く（設定で通常の操縦桿動作に切り替え可）。',
      ],
      terms: [['Attitude', '姿勢', ''], ['Pitch', '縦の傾き（ピッチ）', ''], ['Bank', '横の傾き（バンク）', ''], ['Equilibrium', 'つり合い', ''], ['Trim', 'トリム', ''], ['Control pressure', '操縦の力', ''], ['Power setting', '出力設定', '']],
      examples: ['巡航（教材値 100 kt）：機首をわずかに上げた姿勢、出力約 70 %。高度が下がるなら機首を少し上げ、速度が落ちたら出力を足す。', '速度を上げたら機首下げの力が必要になる → トリムで力を抜く。'],
      cautions: ['トリムで機首の向きを操作しない（まず操縦桿で姿勢、最後にトリム）。', '数値は仮想教材値。実機は POH/AFM と教官の指示による。'],
      quiz: [
        { q: '直線水平飛行で速度を一定に保つとき、推力と抗力の関係は？', choices: ['推力＞抗力', '推力＝抗力（おおむね）', '推力＜抗力', '関係しない'], answer: 1, why: '速度が一定なら加速も減速もしない＝推力と抗力がつり合っている。' },
        { q: 'トリムの正しい使い方は？', choices: ['機首を上げ下げする主な手段', '姿勢と出力を決めた後、操縦桿の力を抜くために使う', '旋回に使う', '使わない方がよい'], answer: 1, why: 'トリムは力を抜く道具。姿勢は操縦桿で作り、安定してからトリムを合わせる。' },
      ],
      refs: [R.afh, R.phak], tasks: ['t1', 't2'],
    }),
    ch({
      no: 7, phase: 'p1', title: '速度と高度のエネルギー管理', en: 'Energy management: airspeed and altitude',
      summary: '速度（運動エネルギー）と高度（位置エネルギー）を交換・補充する考え方を身につける。',
      body: [
        '機体の全エネルギーは「速度（運動エネルギー）」と「高度（位置エネルギー）」の和。機首を下げれば高度を速度に換え、上げれば速度を高度に換える。出力はエネルギーを足し、抗力（フラップ・脚など）は奪う。',
        '<b>例：</b>速度が速すぎて高度も高い進入 → エネルギー過多。出力を絞り、必要なら早めにフラップを使う。速度も高度も足りない → 早めに出力を足す（機首上げだけでは速度を失う）。',
        '<b>トレンド：</b>速度テープや昇降計の変化（傾向）を見て、目標から外れる前に小さく直す。',
        '<b>本アプリ：</b>課題 4「低速から巡航への復帰」と課題 6「最終進入と着陸」でエネルギーの出し入れを練習する。',
      ],
      terms: [['Kinetic energy', '運動エネルギー', '速度'], ['Potential energy', '位置エネルギー', '高度'], ['Total energy', '全エネルギー', ''], ['Trend', '傾向', ''], ['Configuration', '形態（フラップ等）', ''], ['Stabilized approach', '安定した進入', '']],
      examples: ['最終進入で速度 +10 kt・高い：出力を絞って機首をわずかに下げ、降下率を少し増やしながら速度を戻す。', '低速から巡航へ：出力を先に足し、速度が増えるのに合わせて機首を下げ、フラップを段階的に上げる。'],
      cautions: ['低速で機首上げだけで高度を保とうとすると、迎角が増え失速に近づく。', '数値・手順は教材用の近似。実機は教官の指示に従う。'],
      quiz: [
        { q: '進入で「高すぎて速すぎる」ときの基本的な考え方は？', choices: ['出力を足す', 'エネルギー過多なので出力を絞り、抗力を使って減らす', '機首を上げて高度を上げる', '何もしない'], answer: 1, why: '速度も高度も余っている＝エネルギー過多。出力を減らし、フラップなどの抗力でエネルギーを減らす。' },
        { q: '低速で高度を保とうとして機首だけを上げ続けると？', choices: ['速度が増える', '迎角が増え、失速に近づく', '揚力が無限に増える', '燃料が減らない'], answer: 1, why: '出力が足りないまま機首を上げると速度が落ち、同じ揚力のための迎角が増えて臨界迎角に近づく。' },
      ],
      refs: [R.afh], tasks: ['t4', 't6'],
    }),
    ch({
      no: 8, phase: 'p2', title: '旋回・荷重倍数・協調', en: 'Turns, load factor and coordination',
      summary: 'バンクと荷重倍数、失速速度の増加、ラダーによる協調（ボールを中央に）を理解する。',
      body: [
        '<b>旋回：</b>機体を傾けると揚力の向きが傾き、水平方向の成分が機体を曲げる。高度を保つには揚力の縦成分を重力と等しくするため、迎角（背圧）を少し増やす。',
        '<b>荷重倍数：</b>水平旋回の荷重倍数は n = 1 / cos(バンク角)。30° で約 1.15 G、45° で約 1.41 G、60° で 2 G。失速速度は √n 倍になり、60° では約 1.41 倍（約 41 % 増）。',
        '<b>協調（coordination）：</b>エルロンを使うと逆偏揺れ（adverse yaw）で機首が反対に振れる。ラダーで打ち消し、スリップ・スキッド指示（ボール）を中央に保つ（step on the ball）。',
        '<b>本アプリ：</b>PFD のバンク指示の下の台形がスリップ・スキッド指示。設定の「ヨー補助」を OFF にすると、Q/E のラダーで自分で協調させる練習ができる。',
      ],
      terms: [['Load factor', '荷重倍数', 'n = 1/cosφ'], ['Bank angle', 'バンク角', ''], ['Adverse yaw', '逆偏揺れ', ''], ['Coordinated flight', '協調飛行', ''], ['Slip / Skid', '横滑り（内滑り・外滑り）', ''], ['Standard rate turn', '標準旋回率', '3°/秒']],
      examples: ['30° バンクで高度を保つ：わずかに背圧を足す。ロールアウトでは背圧を戻さないと上昇する。', 'ボールが右に寄っている → 右ラダー（Step on the ball）。'],
      cautions: ['低速での急旋回は失速速度が上がり危険。', '本アプリの荷重・失速特性は教材モデルの近似。'],
      quiz: [
        { q: '水平旋回でバンク 60° のときの荷重倍数は？', choices: ['1.0 G', '1.41 G', '2.0 G', '3.0 G'], answer: 2, why: 'n = 1/cos60° = 2.0。' },
        { q: '同じ機体で、バンク 60° の水平旋回の失速速度は直線飛行の約何倍？', choices: ['1.0 倍', '約 1.41 倍', '2 倍', '約 0.7 倍'], answer: 1, why: '失速速度は √n 倍。√2 ≈ 1.41。' },
      ],
      refs: [R.afh, R.phak], tasks: ['t3'],
    }),
    ch({
      no: 9, phase: 'p2', title: '低速・失速兆候', en: 'Slow flight and stall awareness',
      summary: '失速の兆候に気づき、迎角を減らして回復する順序を身につける。',
      body: [
        '<b>兆候：</b>失速警報、操縦の手応えが軽く鈍くなる、機首上げの大きな姿勢、低い速度、バフェット（振動）。本アプリでは失速警報と PFD の AOA（教材）表示で示す。',
        '<b>回復の考え方：</b>FAA の Airplane Flying Handbook の失速回復の手順は、まず迎角を減らす（機首を下げて失速警報が止まるまで）、翼を水平に、必要に応じて出力を足し、目的の飛行経路に戻る。オートパイロットがあれば最初に解除する。',
        '<b>低速飛行：</b>失速の手前で操縦し、出力と姿勢の関係（低速では出力で高度、姿勢で速度の関係が強く出る）を体で覚える。',
        '<b>本アプリ：</b>課題 4「低速から巡航への復帰」。仮想教材値の失速速度は約 48〜53 kt（フラップにより変わる）。',
      ],
      terms: [['Stall warning', '失速警報', ''], ['Buffet', 'バフェット', ''], ['Slow flight', '低速飛行', ''], ['Reduce angle of attack', '迎角を減らす', ''], ['Recovery', '回復', ''], ['Secondary stall', '二次失速', '回復中の急な引き起こし']],
      examples: ['失速警報が鳴った：まず機首を下げて警報を止める → 翼を水平 → 出力 → 上昇へ。', '回復で急に引き起こすと二次失速。速度が戻るのを待って滑らかに。'],
      cautions: ['実機の失速訓練は必ず教官と安全な高度で行う。', '本アプリの失速の挙動は簡略化した教材モデル。'],
      quiz: [
        { q: '失速回復の最初の操作として最も重要なのは？', choices: ['出力を最大にする', '迎角を減らす（機首を下げる）', 'フラップを最大にする', 'バンクを深くする'], answer: 1, why: '失速は迎角が臨界を超えたこと。まず迎角を減らす。出力は次の段階。' },
        { q: '回復中に急に引き起こすと起こり得るのは？', choices: ['二次失速', 'エンジン停止', '燃料漏れ', '高度計の誤差'], answer: 0, why: '速度が十分に戻る前に強く引き起こすと、再び臨界迎角を超える（二次失速）。' },
      ],
      refs: [R.afh], tasks: ['t4'],
    }),
    ch({
      no: 10, phase: 'p2', title: '離陸', en: 'Takeoff',
      summary: '滑走路の中心線を保ち、ローテーション、上昇姿勢、上昇速度の維持までの流れを覚える。',
      body: [
        '<b>流れ：</b>離陸前点検 → 滑走路に正対 → 出力を上げる → 計器（回転数・速度計が動くか）を確認 → 中心線をラダーで保つ → ローテーション速度で機首を上げる → 上昇姿勢 → 上昇速度を保つ。',
        '<b>左偏向傾向：</b>単発プロペラ機は出力を上げると機首が左に振れやすい（P-factor など）。右ラダーで中心線を保つ。本アプリのヨー補助は既定で ON（OFF にすると傾向が強く出る）。',
        '<b>速度（仮想教材値）：</b>Vr 55 kt、Vx 64 kt、Vy 76 kt。実機の値は POH/AFM による。',
        '<b>離陸中止：</b>計器の異常、方向保持ができない、滑走路の残りが少ないなどでは、出力を絞りブレーキ（教材モデルでは Space）。',
        '<b>本アプリ：</b>課題 5 は架空の LAB RWY 36（1,200 m × 30 m、教材値）で行う。Google 3D の背景とは独立している。',
      ],
      terms: [['Takeoff roll', '離陸滑走', ''], ['Centerline', '中心線', ''], ['Rotation (Vr)', '引き起こし', ''], ['Vx / Vy', '最良上昇角速度 / 最良上昇率速度', ''], ['Rejected takeoff', '離陸中止', ''], ['Left-turning tendency', '左偏向傾向', '']],
      examples: ['出力を上げたら機首が左に振れた → 右ラダー。中心線が足の下にあるように。', '55 kt で背圧を増やし、上昇姿勢に。速度が 76 kt に落ち着くようピッチを微調整。'],
      cautions: ['ローテーションで機首を上げすぎると尾部接触・失速の危険。', 'LAB RWY 36 は架空の練習用滑走路で、実在の空港ではない。'],
      quiz: [
        { q: '単発プロペラ機の離陸滑走で、出力を上げたときに機首が振れやすい方向と対処は？', choices: ['右に振れる・左ラダー', '左に振れる・右ラダー', '振れない・何もしない', '上に振れる・エルロン'], answer: 1, why: 'プロペラの影響で左に振れやすい。右ラダーで中心線を保つ。' },
        { q: '最良上昇率速度（Vy）の説明として正しいのは？', choices: ['単位時間あたりに最も高度を得る速度', '単位距離あたりに最も高度を得る速度', '最大の巡航速度', '失速速度'], answer: 0, why: 'Vy は時間あたり（率）、Vx は距離あたり（角）で最も高度を得る速度。' },
      ],
      refs: [R.afh, R.sfb], tasks: ['t5'],
    }),
    ch({
      no: 11, phase: 'p2', title: '着陸', en: 'Landing',
      summary: '安定した最終進入、目標点、引き起こし（フレア）、主輪接地、ゴーアラウンドの判断を学ぶ。',
      body: [
        '<b>安定した進入：</b>中心線上、一定の降下角（本アプリの LOC/GS は 3°）、目標の速度（仮想教材値 66 kt、フルフラップ）、着陸形態が早めに整っていること。外れたらゴーアラウンド。',
        '<b>目標点：</b>フロントガラスの中で目標点が動かなければ、そこに向かっている。上に動けば低すぎ（届かない）、下に動けば高すぎ。',
        '<b>フレア：</b>滑走路の数メートル上で出力を絞り、機首を少しずつ上げて降下を止め、主輪から接地する。前輪から着けない。',
        '<b>本アプリの判定（仮想教材値）：</b>接地直前の降下率が 600 fpm を超えるとハードランディング、1,000 fpm 超は機体損傷。滑走路外への接地・逸脱も記録する。',
      ],
      terms: [['Final approach', '最終進入', ''], ['Aim point', '目標点', ''], ['Flare / Round-out', '引き起こし', ''], ['Touchdown', '接地', ''], ['Go-around', 'ゴーアラウンド', '着陸のやり直し'], ['Runway excursion', '滑走路逸脱', ''], ['Hard landing', 'ハードランディング', '']],
      examples: ['最終進入で目標点が窓の中で上に動く → 低い。出力を少し足す。', 'フレアで浮いた → 引くのを止めて姿勢を保ち、沈み始めたら少しだけ引く。'],
      cautions: ['不安定な進入を無理に続けない。ゴーアラウンドは失敗ではなく正しい判断。', '本アプリの着陸判定は教材用で、実機の基準ではない。'],
      quiz: [
        { q: '最終進入で、フロントガラス上の目標点が下に動いていく。これは？', choices: ['低すぎる', '高すぎる（目標点を越える）', 'ちょうどよい', '速度が遅い'], answer: 1, why: '目標点が下に動く＝その点より先に着く経路＝高すぎる。' },
        { q: '着陸の接地で望ましいのは？', choices: ['前輪から', '主輪から、機首を少し上げた姿勢で', '3 輪同時に強く', '片側の主輪だけ'], answer: 1, why: '主輪から接地する。前輪からの接地は前輪の破損やポーポイズの原因。' },
      ],
      refs: [R.afh], tasks: ['t6'],
    }),
    ch({
      no: 12, phase: 'p3', title: '航法・風・航跡', en: 'Navigation, wind and track',
      summary: '真針路 → 磁針路 → 磁方位（偏流修正）、対地速度と所要時間、目的地変更の考え方を身につける。',
      body: [
        '<b>針路の計算：</b>地図の線は真針路（True Course）。偏差（variation）を加減して磁針路（MC）、風の偏流修正角（WCA）を加えて磁方位（MH）。「East is least, West is best」：西偏差は足す。本アプリの Sanford 周辺の偏差は教材用近似 6°W（実際の値は最新のチャートや NOAA の計算で確認）。',
        '<b>風：</b>機首の向き（HDG）と実際に進む向き（TRK）は風でずれる。PFD の TRK（マゼンタの菱形）が DTK（希望航跡）に重なるよう HDG を決める。',
        '<b>時間：</b>ETE = 距離 ÷ 対地速度。例：12 nm を 96 kt で → 0.125 時間 = 7 分 30 秒。',
        '<b>目的地変更（diversion）：</b>まず機体を飛ばす。新しい目的地のおおよその方位に向け、距離・時間・燃料を概算し、落ち着いてから精度を上げる。ANA の公開情報でも、目的地変更に伴う針路の再計算を訓練するとしている。',
        '<b>現在地を見失ったら：</b>一般に Climb（見通し）・Communicate（交信）・Confess（申告）・Comply（指示に従う）・Conserve（燃料節約）などの考え方が教えられる（本アプリでは架空訓練点で練習）。',
      ],
      terms: [['True course (TC)', '真針路', ''], ['Magnetic variation', '偏差', ''], ['Wind correction angle (WCA)', '偏流修正角', ''], ['Heading (HDG)', '機首方位', ''], ['Track (TRK)', '航跡', ''], ['Desired track (DTK)', '希望航跡', ''], ['Cross-track error (XTK)', '航路からの横ずれ', ''], ['Diversion', '目的地変更', ''], ['ETE', '所要時間', '']],
      examples: ['TC 054°、偏差 6°W → MC 060°。右から風（WCA +5°）→ MH 065°。', 'LAB-A から LAB-C へ変更：D→ で直行し、MFD の DIS と ETE で燃料と時間を確認。'],
      cautions: ['架空訓練点は実在の地点ではない。実際の航法には最新の航空図を使う。', '偏差は場所と年で変わる。'],
      quiz: [
        { q: '真針路 090°、偏差 6°W のときの磁針路は？', choices: ['084°', '090°', '096°', '270°'], answer: 2, why: '西偏差は足す（West is best）：090 + 6 = 096°。' },
        { q: '距離 15 nm、対地速度 90 kt の所要時間は？', choices: ['6 分', '10 分', '15 分', '90 分'], answer: 1, why: '15 ÷ 90 = 1/6 時間 = 10 分。' },
      ],
      refs: [R.phak, R.ana1, R.mag, R.vfr], tasks: ['t7', 't8', 't9'],
    }),
    ch({
      no: 13, phase: 'p4', title: '計器走査', en: 'Instrument scan',
      summary: '姿勢指示器を中心にした走査、主計器と補助計器、走査の誤り（固視・見落とし・偏り）を学ぶ。',
      body: [
        '<b>走査（cross-check）：</b>姿勢指示器を中心に、速度・高度・昇降計・方位へ視線を往復させる（放射状の走査）。FAA の Instrument Flying Handbook は、姿勢指示器を中心にした走査と、各計器の「主（primary）・補助（supporting）」の考え方を説明している。',
        '<b>よくある誤り：</b>固視（fixation：1 つの計器を見続ける）、見落とし（omission）、偏り（emphasis：1 つの計器に頼りすぎる）。',
        '<b>計器による変更：</b>旋回なら姿勢指示器でバンクを作り、方位指示で目標の手前からロールアウトを始める（目安：バンク角の半分程度手前）。上昇・降下は姿勢と出力を変え、選択高度の手前で水平に移る。',
        '<b>本アプリ：</b>課題 10・11 は外の景色を隠す「フード」状態。HDG バグと選択高度は目印で、機体は自動では追従しない（オートパイロットは未実装）。',
      ],
      terms: [['Instrument cross-check / scan', '計器走査', ''], ['Primary / Supporting instruments', '主計器 / 補助計器', ''], ['Fixation', '固視', ''], ['Omission', '見落とし', ''], ['Emphasis', '偏り', ''], ['Spatial disorientation', '空間識失調', ''], ['Hood (view limiting device)', 'フード（視界制限）', '']],
      examples: ['方位 360° → 090° へ：バンク 15° 程度を作り、075° 付近からロールアウトを始める。', '2,000 → 2,500 ft：機首を数度上げ出力を足す。2,450 ft 付近から水平へ移る。'],
      cautions: ['体の感覚より計器を信じる（空間識失調）。', '実機の計器飛行訓練は資格ある教官の下で行う。'],
      quiz: [
        { q: '計器走査の中心に置く計器は？', choices: ['燃料計', '姿勢指示器', '時計', '油温計'], answer: 1, why: '姿勢指示器を中心に、他の計器へ視線を往復させる。' },
        { q: '1 つの計器を見続けて他を見なくなる誤りは？', choices: ['固視（fixation）', '見落とし（omission）', '協調', 'トリム'], answer: 0, why: '固視は 1 つの計器に視線が固定され、他の変化に気づけなくなる誤り。' },
      ],
      refs: [R.ifh, R.ana1], tasks: ['t10', 't11'],
    }),
    ch({
      no: 14, phase: 'p3', title: '異常時の優先順位', en: 'Priorities in abnormal situations',
      summary: 'まず飛ばす（Aviate）、次に航法（Navigate）、そして交信（Communicate）。エンジン停止時の滑空を練習する。',
      body: [
        '<b>優先順位：</b>Aviate（機体を飛ばす）→ Navigate（どこへ向かうか）→ Communicate（伝える）。どんな異常でも、まず機体の姿勢と速度を保つ。',
        '<b>エンジン停止（単発）：</b>一般に教えられる考え方として、最良滑空速度を作る → 降りる場所を選ぶ → チェックリスト（再始動の試みなど）→ 宣言（メーデー・トランスポンダ）→ 実行。手順そのものは機体の POH/AFM のチェックリストに従う。',
        '<b>公開情報：</b>ANA の基礎訓練の Navigation 訓練では、飛行中のエンジン停止を想定した訓練、現在地を見失った場合の対処なども並行して行う。',
        '<b>本アプリ：</b>課題 12「エンジン停止後の滑空」。仮想教材値の最良滑空速度は 76 kt。',
      ],
      terms: [['Aviate, Navigate, Communicate', '飛ばす・航法・交信', ''], ['Best glide speed', '最良滑空速度', ''], ['Forced landing', '不時着', ''], ['Checklist', 'チェックリスト', ''], ['Mayday / Pan-pan', '遭難・緊急通報', ''], ['Squawk 7700', '緊急のトランスポンダ符号', '']],
      examples: ['エンジン停止：まず 76 kt（教材値）の姿勢を作る → 風上側の広い場所 → チェックリスト。', '無線の周波数を探して機首を下げすぎた → 本末転倒。Aviate が先。'],
      cautions: ['実機の緊急手順は POH/AFM と教官の指示に従う。本アプリの手順は概念の練習。', 'エンジン停止は高度と時間が限られる。早めの決断。'],
      quiz: [
        { q: '異常が起きたときの基本の優先順位は？', choices: ['Communicate → Navigate → Aviate', 'Aviate → Navigate → Communicate', 'Navigate → Aviate → Communicate', 'どれでもよい'], answer: 1, why: 'まず機体を飛ばす。航法・交信はその後。' },
        { q: '単発機のエンジン停止直後に最初にすることは？', choices: ['無線で周波数を探す', '最良滑空速度の姿勢を作る', 'フラップを最大にする', '燃料を捨てる'], answer: 1, why: '速度と姿勢を保つ（Aviate）。滑空速度を作ってから場所選び・チェックリスト。' },
      ],
      refs: [R.afh, R.ana1], tasks: ['t12'],
    }),
    ch({
      no: 15, phase: 'p5', title: 'Seminole・双発機への移行', en: 'Transition to the Seminole (multi-engine)',
      summary: '双発機の特徴、片発停止時の考え方（Vmc、Vyse、識別・確認・フェザー）を概念として学ぶ。',
      body: [
        '<b>事実（公開情報）：</b>Piper Seminole は Lycoming IO-360 エンジン 2 基（各 180 hp）、定速・フルフェザー式プロペラ、G1000 NXi 標準（Piper 公式）。Acron Aviation の紹介では、エンジン停止訓練の安定性のための二重反転（counter-rotating）プロペラを挙げている。ANA の公開情報では、Seminole で片方のエンジンが止まった時や様々な故障の対応を訓練する。',
        '<b>片発停止の考え方（一般）：</b>片側の推力が失われると機首がそちらへ振れ、生きている側のラダーで止める（Dead foot, dead engine：力を入れていない足の側が止まったエンジン）。識別（Identify）→ 確認（Verify）→ フェザー（Feather）。',
        '<b>速度：</b>Vmc（最小操縦速度、赤線）より遅くしない。片発での最良上昇率速度 Vyse（青線）。値は機体の POH/AFM による。',
        '<b>本アプリ：</b>飛行モデルは単発機のみ。双発の挙動は実装していない（未実装）。この章は概念の予習。',
      ],
      terms: [['Multi-engine', '多発（双発）', ''], ['Vmc', '最小操縦速度', '赤線'], ['Vyse', '片発最良上昇率速度', '青線'], ['Feather', 'フェザー', ''], ['Identify, Verify, Feather', '識別・確認・フェザー', ''], ['Counter-rotating propellers', '二重反転（左右逆回転）プロペラ', ''], ['Critical engine', '臨界発動機', '']],
      examples: ['右エンジン停止 → 機首が右へ → 左ラダー（踏んでいる足＝生きている側）→ 右足が遊ぶ＝右エンジンが止まっている（Dead foot, dead engine）。', '片発時は速度を Vmc より十分上に保ち、Vyse を目安にする。'],
      cautions: ['本アプリに双発機の飛行モデルはない（概念のみ）。', '値と手順は機体の POH/AFM と教官に従う（機体ごとに要確認）。'],
      quiz: [
        { q: '「Dead foot, dead engine」の意味は？', choices: ['力を入れていない足の側のエンジンが止まっている', '両足が疲れたら着陸する', '右足は常に止まったエンジン側', 'ラダーは使わない'], answer: 0, why: '生きているエンジン側のラダーを踏むので、踏んでいない（遊んでいる）足の側が止まったエンジン。' },
        { q: '双発機の速度計の赤線（Vmc）より遅くすると？', choices: ['燃費がよくなる', '片発時に方向を保てなくなるおそれがある', '失速しなくなる', '何も変わらない'], answer: 1, why: 'Vmc は片発時に方向を保てる最小の速度。下回ると操縦できなくなるおそれ。' },
      ],
      refs: [R.seminole, R.acron, R.ana1, R.afh], tasks: [],
    }),
    ch({
      no: 16, phase: 'p6', title: '気象・重量重心・CRM・TEM', en: 'Weather, weight & balance, CRM, TEM',
      summary: 'フライトを支える知識と、エアラインへつながる考え方（CRM・TEM・自動化）を概観する。',
      body: [
        '<b>気象：</b>METAR / TAF の読み方、雷雨（夏のフロリダでは午後の対流雲に注意するのが一般的）、視程と雲高。FAA の Aviation Weather Handbook が基本資料。',
        '<b>重量重心：</b>重量と重心位置が限界内にあることを毎回確認する。重心が前すぎると引き起こしが重く、後ろすぎると安定性が下がる（FAA Weight and Balance Handbook）。',
        '<b>CRM（Crew Resource Management）：</b>人・機材・情報のすべてを使って安全な判断をする。言うべきことは言い、聞くべきことは聴く。ANA の現地取材記事でも、運航品質とコミュニケーションのバランス、判断の説明責任が語られている。',
        '<b>TEM（Threat and Error Management）：</b>脅威（天候、混雑した空域、疲労など）を予測し、エラーを捕まえ、望ましくない機体状態を避ける考え方（SKYbrary）。',
        '<b>ジェット機・自動化への準備：</b>自動化は便利だが、「今、何のモードで、次に何をするか」を常に把握する。小型機での手動操縦と計器走査の基礎が土台になる。本アプリにオートパイロットはない（未実装）。',
      ],
      terms: [['METAR / TAF', '定時気象報 / 飛行場予報', ''], ['Thunderstorm', '雷雨', ''], ['Center of gravity (CG)', '重心', ''], ['Weight and balance', '重量重心', ''], ['CRM', 'クルー・リソース・マネジメント', ''], ['TEM', '脅威とエラーのマネジメント', ''], ['Undesired aircraft state', '望ましくない機体状態', ''], ['Mode awareness', 'モードの把握', '']],
      examples: ['TEM：出発前ブリーフィングで「午後の雷雨・混雑する Sanford の場周・慣れない英語交信」を脅威として挙げ、対策（早めの出発、復唱の準備、ゴーアラウンドの基準）を決める。', 'CRM：教官や相手の言ったことを復唱して確認し、疑問はその場で質問する。'],
      cautions: ['本章は概観。実際の気象判断・重量重心計算は資料と教官の指示で行う。', '本アプリは ANA の CRM / TEM プログラムを再現していない。'],
      quiz: [
        { q: 'TEM の「脅威（threat）」の例として適切なのは？', choices: ['悪天候や混雑した空域', 'パイロットの復唱', '着陸後の駐機', '燃料の補給'], answer: 0, why: '脅威は操縦者の外からやってきて、安全の余裕を減らす要因（天候、交通、時間の圧力など）。' },
        { q: '重心が後方限界を超えると起こりやすいことは？', choices: ['安定性が低下し、操縦が過敏になる', '引き起こしが重くなる', '燃料が減らない', '影響はない'], answer: 0, why: '後方重心では縦の安定性が下がり、失速からの回復も難しくなる。前方重心では引き起こしが重くなる。' },
      ],
      refs: [R.wx, R.wb, R.crm, R.tem, R.rmh, R.ana2], tasks: [],
    }),
  ];
  FL.curriculum = { R, PHASES, CHAPTERS };
})(typeof globalThis !== 'undefined' ? (globalThis.FL = globalThis.FL || {}) : {});
